version: '3.9'

services:
  server:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - media_volume:/django-app/media
      - static_volume:/django-app/staticfiles
    expose:
      - 8080
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    restart: always
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:14.8
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - static_volume:/django-app/staticfiles
      - media_volume:/django-app/media
    
  celery-worker:
    build: 
     context: ./app
    command: celery -A monitoring worker
    depends_on:
      - server
    env_file:
      - .env

  celery-beat:
    restart: always
    build: 
      context: ./app
    command: celery -A monitoring beat
    volumes:
      - beat_volume:/django-app
    depends_on:
      - celery-worker
    env_file:
      - .env

volumes:
  postgres_data:
  media_volume:
  static_volume:
  beat_volume: