# Generated by Django 4.2.3 on 2023-08-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_social',
            field=models.BooleanField(default=True),
        ),
    ]
