# Generated by Django 4.2.3 on 2023-08-02 15:43

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('image', models.ImageField(upload_to='article_images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Carouser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='ServerScreenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('short_description', models.CharField(max_length=2000)),
                ('server_site', models.CharField(max_length=1000)),
                ('server_discord', models.CharField(max_length=1000)),
                ('full_description', models.TextField()),
                ('version', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=1000)),
                ('is_icon_auto', models.BooleanField()),
                ('server_banner', models.FileField(upload_to='banners/%Y/%m/%d')),
                ('curr_online', models.IntegerField()),
                ('max_online', models.IntegerField()),
                ('diamonds', models.IntegerField()),
                ('carousel', models.ManyToManyField(related_name='server_carousel', to='serversApp.carouser')),
                ('owners', models.ManyToManyField(related_name='servers', to=settings.AUTH_USER_MODEL)),
                ('screenshots', models.ManyToManyField(related_name='server_screenshots', to='serversApp.serverscreenshots')),
            ],
        ),
    ]
