# Generated by Django 4.2.3 on 2023-08-02 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serversApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Статті'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name_plural': 'Сервери'},
        ),
        migrations.AddField(
            model_name='server',
            name='added',
            field=models.ManyToManyField(related_name='added_servers', to=settings.AUTH_USER_MODEL),
        ),
    ]
