# Generated by Django 4.2.3 on 2023-08-02 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serversApp', '0002_alter_article_options_alter_server_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='added',
            field=models.ManyToManyField(blank=True, related_name='added_servers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='server',
            name='carousel',
            field=models.ManyToManyField(blank=True, related_name='server_carousel', to='serversApp.carouser'),
        ),
        migrations.AlterField(
            model_name='server',
            name='curr_online',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='diamonds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='max_online',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='servers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='server',
            name='screenshots',
            field=models.ManyToManyField(blank=True, related_name='server_screenshots', to='serversApp.serverscreenshots'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_banner',
            field=models.FileField(blank=True, null=True, upload_to='banners/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_discord',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_site',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='short_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
