# Generated by Django 4.2.3 on 2023-08-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversApp', '0003_alter_server_added_alter_server_carousel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='logos/%Y/%m/%d'),
        ),
    ]
