# Generated by Django 4.2.3 on 2023-08-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversApp', '0004_server_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default='qwe'),
        ),
    ]
