# Generated by Django 4.2.3 on 2023-08-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversApp', '0005_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(),
        ),
    ]
