# Generated by Django 4.2.3 on 2023-08-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversApp', '0006_alter_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
