# Generated by Django 4.2.3 on 2023-08-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversApp', '0007_server_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='uptime',
            field=models.FloatField(default=100),
        ),
    ]
