# Generated by Django 4.2.3 on 2023-08-03 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversApp', '0008_server_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 13, 55, 5, 685083, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='server',
            name='last_check',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 13, 55, 5, 685070, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='server',
            name='uptime',
            field=models.FloatField(default=0),
        ),
    ]
