# Generated by Django 4.2.3 on 2023-08-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversApp', '0010_alter_server_created_at_alter_server_last_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='is_icon_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
