# Generated by Django 4.2.3 on 2023-08-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversApp', '0011_alter_server_is_icon_auto_alter_server_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
