# Generated by Django 4.2.3 on 2023-08-05 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serversApp', '0012_donates_alter_server_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='who_polled',
            field=models.ManyToManyField(related_name='polled', to=settings.AUTH_USER_MODEL),
        ),
    ]
